# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  name: Fortify
steps:
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: 'java -jar /opt/fortify-api-client-latest.jar create -n $(Build.Repository.Name) -v $(Build.SourceBranchName)'
# - task: Bash@3
#   inputs:
#     targetType: 'inline'
#     script: |
#       var=$(/opt/sca/bin/scancentral -sscurl $(var.sscurl) -ssctoken $(var.ssctoken) start -bt none -upload --application $(Build.Repository.Name) --application-version $(Build.SourceBranchName) -uptoken $(var.uptoken)) && jobtoken=${var:(-36)} && echo jobtoken: $jobtoken
#       while true; do
#           jobStatus=$(java -jar /opt/fortify-api-client-latest.jar checkCloudscanStatus -jt $jobtoken)
#           echo jobStatus $jobStatus
#           if expr ${jobStatus//[[:space:]]/} : ".*COMPLETED*."; then
#               echo "Cloudscan Job completed."
#               sleep 10
#               break
#           elif expr ${jobStatus//[[:space:]]/} : ".*ERROR.*" || expr ${jobStatus//[[:space:]]/} : ".*FAILED.*" || expr ${jobStatus//[[:space:]]/} : ".*FAULTED.*" || expr ${jobStatus//[[:space:]]/} : ".*CANCELED.*"; then
#               echo "Erro ao executar o scan. Current status: $jobStatus. Consulte os logs do Fortify para obter mais detalhes."
#               exit
#           else
#               echo "Waiting job to process. Current status: $jobStatus"
#               sleep 30
#           fi
#       done
- task: Bash@3
  displayName: 'Debricked scan'
  inputs:
    targetType: 'inline'
    script: |
      echo "starting scan debricked"
      env > env.list
      docker run -v $HOME:$HOME --env-file ./env.list --entrypoint "/azure-devops.sh" debricked/debricked-scan:latest
  env:
    var.debricked: $(DEBRICKED_TOKEN_3)