# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:

- main

pool:
  name: Fortify
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'java -jar /opt/fortify-api-client-latest.jar create -n $(Build.Repository.Name) -v $(Build.SourceBranchName)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script:  /opt/sca/scancentral -sscurl $(var.sscurl) -ssctoken $(var.ssctoken) start -bt none -upload --application $(Build.Repository.Name) --application-version $(Build.SourceBranchName) -uptoken $(var.uptoken) 